window.SITE_NAV = {
  "siteTitle": "La Tierra del Indalo",
  "tagline": "Matemáticas · 1.º ESO",
  "project": "indalo",
  "groupOrder": [
    "Presentación",
    "Contexto",
    "Teoría",
    "Laboratorio",
    "Ejercicios",
    "Evaluación",
    "Material docente"
  ],
  "navLabels": {
    "Presentación": "Inicio",
    "Material docente": "Docentes"
  },
  "sectionDescriptions": {
    "Presentación": "Portada y entrada general al proyecto.",
    "Contexto": "Misión, hoja de ruta y marco social del itinerario.",
    "Teoría": "Contenidos conceptuales y materiales de repaso.",
    "Laboratorio": "Juegos matemáticos y experiencias interactivas.",
    "Ejercicios": "Práctica guiada, problemas y consolidación.",
    "Evaluación": "Tests y simulación de examen en modo local.",
    "Material docente": "Documentación pedagógica para su implementación."
  },
  "featured": [
    "inicio",
    "ruta",
    "laboratorio-fracciones-el-igualador-de-fracciones-1-0",
    "laboratorio-proporciones-agro-manager",
    "evaluacion-tests",
    "evaluacion-examen"
  ],
  "pages": [
    {
      "id": "inicio",
      "label": "Inicio",
      "title": "Inicio - Matemáticas en la Tierra del Indalo",
      "summary": "Portada visual del proyecto y acceso a la secuencia didáctica.",
      "group": "Presentación",
      "subgroup": "Núcleo",
      "tone": "tierra",
      "path": "pages/inicio.html",
      "order": 0
    },
    {
      "id": "mision",
      "label": "Misión",
      "title": "Contexto y Misión - Matemáticas en la Tierra del Indalo",
      "summary": "Contexto narrativo y propósito de la experiencia de aprendizaje.",
      "group": "Contexto",
      "subgroup": "Proyecto",
      "tone": "tierra",
      "path": "pages/mision.html",
      "order": 1
    },
    {
      "id": "ruta",
      "label": "Hoja de Ruta",
      "title": "Hoja de Ruta - Secuencia Didáctica",
      "summary": "Secuencia completa de sesiones, hitos y momentos de evaluación.",
      "group": "Contexto",
      "subgroup": "Proyecto",
      "tone": "mediterraneo",
      "path": "pages/ruta.html",
      "order": 2
    },
    {
      "id": "mar-de-plastico",
      "label": "Mar de Plástico",
      "title": "El Lado Humano - Conciencia Social",
      "summary": "Marco social y territorial vinculado al proyecto.",
      "group": "Contexto",
      "subgroup": "Proyecto",
      "tone": "invernadero",
      "path": "pages/mar-de-plastico.html",
      "order": 3
    },
    {
      "id": "para-docentes",
      "label": "Material Docente",
      "title": "SdA: Matemáticas en la Tierra del Indalo",
      "summary": "Síntesis pedagógica y organizativa para su implantación en aula.",
      "group": "Material docente",
      "subgroup": "Diseño",
      "tone": "grafito",
      "path": "pages/para-docentes.html",
      "order": 4
    },
    {
      "id": "aportaciones-desde-otras-materias",
      "label": "Aportaciones desde otras materias",
      "title": "Aportaciones desde otras materias - La Tierra del Indalo",
      "summary": "Ideas para coordinar la situación de aprendizaje con el resto de materias de 1.º de ESO.",
      "group": "Material docente",
      "subgroup": "Diseño",
      "tone": "grafito",
      "path": "pages/aportaciones-desde-otras-materias.html",
      "order": 5
    },
    {
      "id": "teoria-el-manual-del-arquitecto-y-el-agricultor",
      "label": "Manual General",
      "title": "Teoría Matemática - Manual del Arquitecto y Agricultor",
      "summary": "Contenido teórico del bloque «Manual General».",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/el-manual-del-arquitecto-y-el-agricultor.html",
      "order": 6
    },
    {
      "id": "teoria-1-mosaicos-y-fracciones",
      "label": "Mosaicos y Fracciones",
      "title": "Teoría: Mosaicos y Fracciones",
      "summary": "Contenido teórico del bloque «Mosaicos y Fracciones».",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/1-mosaicos-y-fracciones.html",
      "order": 7
    },
    {
      "id": "teoria-2-el-laboratorio-de-las-proporciones",
      "label": "El Laboratorio de las Proporciones",
      "title": "Teoría: Proporciones y NPK",
      "summary": "Contenido teórico del bloque «El Laboratorio de las Proporciones».",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/2-el-laboratorio-de-las-proporciones.html",
      "order": 8
    },
    {
      "id": "teoria-3-el-lenguaje-del-inverandero",
      "label": "El lenguaje del Inverandero",
      "title": "Teoría: Lenguaje Algebraico",
      "summary": "Contenido teórico del bloque «El lenguaje del Inverandero».",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/3-el-lenguaje-del-inverandero.html",
      "order": 9
    },
    {
      "id": "teoria-4-taller-de-algebra",
      "label": "Taller de Álgebra",
      "title": "Taller de Álgebra - Mates Indalo",
      "summary": "Contenido teórico del bloque «Taller de Álgebra».",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/4-taller-de-algebra.html",
      "order": 10
    },
    {
      "id": "teoria-5-la-balanza-de-costes",
      "label": "La Balanza de Costes",
      "title": "Teoría: Ecuaciones y Costes",
      "summary": "Contenido teórico del bloque «La Balanza de Costes».",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/5-la-balanza-de-costes.html",
      "order": 11
    },
    {
      "id": "teoria-resumen",
      "label": "Resumen",
      "title": "Resumen: Esquema Matemático Actualizado",
      "summary": "Resumen imprimible de conceptos clave de fracciones, proporciones y álgebra.",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/resumen.html",
      "order": 12
    },
    {
      "id": "teoria-flashcards",
      "label": "Flashcards",
      "title": "Flashcards: Matemáticas 1º ESO",
      "summary": "Tarjetas de repaso rápido para consolidar vocabulario y procedimientos.",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/flashcards.html",
      "order": 13
    },
    {
      "id": "teoria-cazador-de-errores",
      "label": "Cazador de Errores",
      "title": "Errores Comunes y Soluciones",
      "summary": "Galería de errores habituales con explicación y corrección.",
      "group": "Teoría",
      "subgroup": "Bloques conceptuales",
      "tone": "nazar",
      "path": "pages/teoria/cazador-de-errores.html",
      "order": 14
    },
    {
      "id": "laboratorio-fracciones-el-igualador-de-fracciones-2-0",
      "label": "El Igualador de Fracciones 2.0",
      "title": "Laboratorio de Equivalencias",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-igualador-de-fracciones-2-0.html",
      "order": 15
    },
    {
      "id": "laboratorio-fracciones-el-igualador-de-fracciones-1-0",
      "label": "El Igualador de Fracciones 1.0",
      "title": "Laboratorio de Fracciones 2.0 - Vasos de Agua",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-igualador-de-fracciones-1-0.html",
      "order": 16
    },
    {
      "id": "laboratorio-fracciones-el-muro-nazari-1-0",
      "label": "El Muro Nazarí 1.0",
      "title": "Muro Nazarí 1.0: Suma de Fracciones",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-muro-nazari-1-0.html",
      "order": 17
    },
    {
      "id": "laboratorio-fracciones-el-muro-nazari-2-0",
      "label": "El Muro Nazarí 2.0",
      "title": "Laboratorio: El Muro Nazarí",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-muro-nazari-2-0.html",
      "order": 18
    },
    {
      "id": "laboratorio-fracciones-el-muro-nazari-3-0",
      "label": "El Muro Nazarí 3.0",
      "title": "Laboratorio 2.0: Fracciones Impropias",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-muro-nazari-3-0.html",
      "order": 19
    },
    {
      "id": "laboratorio-fracciones-el-huerto-del-indalo",
      "label": "El Huerto del Indalo",
      "title": "Laboratorio: El Huerto Geométrico",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-huerto-del-indalo.html",
      "order": 20
    },
    {
      "id": "laboratorio-fracciones-desafio-de-la-cosecha",
      "label": "Desafío de la Cosecha",
      "title": "Campaña: El Huerto Matemático",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/desafio-de-la-cosecha.html",
      "order": 21
    },
    {
      "id": "laboratorio-fracciones-el-cortador-de-tuberias",
      "label": "El Cortador de Tuberías",
      "title": "Laboratorio: El Cortador de Tuberías",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/el-cortador-de-tuberias.html",
      "order": 22
    },
    {
      "id": "laboratorio-fracciones-riego-de-alta-precision",
      "label": "Riego de Alta Precisión",
      "title": "Laboratorio: Instalador de Riego (Nivel Experto)",
      "summary": "Actividad interactiva del laboratorio de fracciones.",
      "group": "Laboratorio",
      "subgroup": "Fracciones",
      "tone": "nazar",
      "path": "pages/laboratorio/fracciones/riego-de-alta-precision.html",
      "order": 23
    },
    {
      "id": "laboratorio-proporciones-calculadora-de-fertirrigacion",
      "label": "Calculadora de Fertirrigación",
      "title": "Laboratorio: Calculadora de Riego NPK",
      "summary": "Actividad interactiva del laboratorio de proporciones.",
      "group": "Laboratorio",
      "subgroup": "Proporciones",
      "tone": "invernadero",
      "path": "pages/laboratorio/proporciones/calculadora-de-fertirrigacion.html",
      "order": 24
    },
    {
      "id": "laboratorio-proporciones-balsa-de-riego",
      "label": "Balsa de Riego",
      "title": "Laboratorio: Proporcionalidad Inversa",
      "summary": "Actividad interactiva del laboratorio de proporciones.",
      "group": "Laboratorio",
      "subgroup": "Proporciones",
      "tone": "invernadero",
      "path": "pages/laboratorio/proporciones/balsa-de-riego.html",
      "order": 25
    },
    {
      "id": "laboratorio-proporciones-cultivo-en-invernadero-1-0",
      "label": "Cultivo en Invernadero 1.0",
      "title": "El Arquitecto de Invernaderos",
      "summary": "Actividad interactiva del laboratorio de proporciones.",
      "group": "Laboratorio",
      "subgroup": "Proporciones",
      "tone": "invernadero",
      "path": "pages/laboratorio/proporciones/cultivo-en-invernadero-1-0.html",
      "order": 26
    },
    {
      "id": "laboratorio-proporciones-cultivo-en-invernadero-2-0",
      "label": "Cultivo en Invernadero 2.0",
      "title": "Cooperativa Agrícola - Gestión de Pedidos",
      "summary": "Actividad interactiva del laboratorio de proporciones.",
      "group": "Laboratorio",
      "subgroup": "Proporciones",
      "tone": "invernadero",
      "path": "pages/laboratorio/proporciones/cultivo-en-invernadero-2-0.html",
      "order": 27
    },
    {
      "id": "laboratorio-proporciones-agro-manager",
      "label": "Agro Manager",
      "title": "Gestión Dinámica del Invernadero",
      "summary": "Actividad interactiva del laboratorio de proporciones.",
      "group": "Laboratorio",
      "subgroup": "Proporciones",
      "tone": "invernadero",
      "path": "pages/laboratorio/proporciones/agro-manager.html",
      "order": 28
    },
    {
      "id": "laboratorio-algebra-conector-algebraico",
      "label": "Conector Algebraico",
      "title": "Laboratorio: Traductor Algebraico",
      "summary": "Actividad interactiva del laboratorio de álgebra.",
      "group": "Laboratorio",
      "subgroup": "Álgebra",
      "tone": "cobalto",
      "path": "pages/laboratorio/algebra/conector-algebraico.html",
      "order": 29
    },
    {
      "id": "laboratorio-algebra-el-traductor-algebraico",
      "label": "El Traductor Algebraico",
      "title": "El Traductor Algebraico",
      "summary": "Actividad interactiva del laboratorio de álgebra.",
      "group": "Laboratorio",
      "subgroup": "Álgebra",
      "tone": "cobalto",
      "path": "pages/laboratorio/algebra/el-traductor-algebraico.html",
      "order": 30
    },
    {
      "id": "laboratorio-algebra-suma-de-monomios",
      "label": "Suma de Monomios",
      "title": "Laboratorio de Álgebra",
      "summary": "Actividad interactiva del laboratorio de álgebra.",
      "group": "Laboratorio",
      "subgroup": "Álgebra",
      "tone": "cobalto",
      "path": "pages/laboratorio/algebra/suma-de-monomios.html",
      "order": 31
    },
    {
      "id": "laboratorio-algebra-el-centro-logistico-de-la-cooperativa",
      "label": "El Centro Logístico de la Cooperativa",
      "title": "Laboratorio: Suma de Polinomios (Completo)",
      "summary": "Actividad interactiva del laboratorio de álgebra.",
      "group": "Laboratorio",
      "subgroup": "Álgebra",
      "tone": "cobalto",
      "path": "pages/laboratorio/algebra/el-centro-logistico-de-la-cooperativa.html",
      "order": 32
    },
    {
      "id": "laboratorio-algebra-detective-de-ecuaciones",
      "label": "Detective de ecuaciones",
      "title": "Laboratorio: El Detective de Errores",
      "summary": "Actividad interactiva del laboratorio de álgebra.",
      "group": "Laboratorio",
      "subgroup": "Álgebra",
      "tone": "cobalto",
      "path": "pages/laboratorio/algebra/detective-de-ecuaciones.html",
      "order": 33
    },
    {
      "id": "laboratorio-ecuaciones-la-balanza-algebraica-1-0",
      "label": "La Balanza Algebráica 1.0",
      "title": "Laboratorio: La Balanza Algebraica",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/la-balanza-algebraica-1-0.html",
      "order": 34
    },
    {
      "id": "laboratorio-ecuaciones-la-balanza-algebraica-2-0",
      "label": "La Balanza Algebráica 2.0",
      "title": "Laboratorio: La Balanza Algebraica 2.0",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/la-balanza-algebraica-2-0.html",
      "order": 35
    },
    {
      "id": "laboratorio-ecuaciones-la-balanza-algebraica-3-0",
      "label": "La Balanza Algebráica 3.0",
      "title": "Laboratorio: La Balanza Algebraica 3.0",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/la-balanza-algebraica-3-0.html",
      "order": 36
    },
    {
      "id": "laboratorio-ecuaciones-la-balanza-algebraica-4-0",
      "label": "La Balanza Algebráica 4.0",
      "title": "Laboratorio: La Balanza Algebraica 4.0",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/la-balanza-algebraica-4-0.html",
      "order": 37
    },
    {
      "id": "laboratorio-ecuaciones-laberinto-de-puertas",
      "label": "Laberinto de Puertas",
      "title": "Laboratorio: El Laberinto de las Puertas",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/laberinto-de-puertas.html",
      "order": 38
    },
    {
      "id": "laboratorio-ecuaciones-detective-de-ecuaciones",
      "label": "Detective de ecuaciones",
      "title": "Laboratorio: El Detective de Errores",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/detective-de-ecuaciones.html",
      "order": 39
    },
    {
      "id": "laboratorio-ecuaciones-el-modelo-de-la-cebolla",
      "label": "El Modelo de la Cebolla",
      "title": "Laboratorio: El Modelo de la Cebolla",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/el-modelo-de-la-cebolla.html",
      "order": 40
    },
    {
      "id": "laboratorio-ecuaciones-caja-fuerte-de-incognitas",
      "label": "Caja Fuerte de Incógnitas",
      "title": "Laboratorio: La Caja Fuerte Matemática",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/caja-fuerte-de-incognitas.html",
      "order": 41
    },
    {
      "id": "laboratorio-ecuaciones-el-rio-de-las-ecuaciones",
      "label": "El Río de las Ecuaciones",
      "title": "Laboratorio: El Río de las Ecuaciones",
      "summary": "Actividad interactiva del laboratorio de ecuaciones.",
      "group": "Laboratorio",
      "subgroup": "Ecuaciones",
      "tone": "bronce",
      "path": "pages/laboratorio/ecuaciones/el-rio-de-las-ecuaciones.html",
      "order": 42
    },
    {
      "id": "laboratorio-tablas-de-multiplicar",
      "label": "Tablas de Multiplicar",
      "title": "Laboratorio: Tablas de Multiplicar",
      "summary": "Actividad interactiva del laboratorio de general.",
      "group": "Laboratorio",
      "subgroup": "General",
      "tone": "mediterraneo",
      "path": "pages/laboratorio/general/tablas-de-multiplicar.html",
      "order": 43
    },
    {
      "id": "ejercicios-problemas",
      "label": "Problemas",
      "title": "Hoja de Retos Progresivos - Matemáticas Indalo",
      "summary": "Práctica guiada y autónoma en «Problemas».",
      "group": "Ejercicios",
      "subgroup": "Práctica",
      "tone": "grafito",
      "path": "pages/ejercicios/problemas.html",
      "order": 44
    },
    {
      "id": "ejercicios-propuestos-con-ayuda",
      "label": "Propuestos con ayuda",
      "title": "Cuaderno de Ejercicios - Matemáticas Indalo",
      "summary": "Práctica guiada y autónoma en «Propuestos con ayuda».",
      "group": "Ejercicios",
      "subgroup": "Práctica",
      "tone": "grafito",
      "path": "pages/ejercicios/propuestos-con-ayuda.html",
      "order": 45
    },
    {
      "id": "ejercicios-resueltos",
      "label": "Resueltos",
      "title": "Banco de Ejercicios Resueltos - Mates Indalo",
      "summary": "Práctica guiada y autónoma en «Resueltos».",
      "group": "Ejercicios",
      "subgroup": "Práctica",
      "tone": "grafito",
      "path": "pages/ejercicios/resueltos.html",
      "order": 46
    },
    {
      "id": "evaluacion-tests",
      "label": "Tests",
      "title": "Aula Virtual - Evaluación Matemática",
      "summary": "Cuestionarios autocorregibles en modo local y sin envío de datos.",
      "group": "Evaluación",
      "subgroup": "Seguimiento",
      "tone": "dorado",
      "path": "pages/evaluacion/tests.html",
      "order": 47
    },
    {
      "id": "evaluacion-examen",
      "label": "Examen",
      "title": "Examen Interactivo",
      "summary": "Simulador avanzado de evaluación modular en modo demostración.",
      "group": "Evaluación",
      "subgroup": "Seguimiento",
      "tone": "dorado",
      "path": "pages/evaluacion/examen.html",
      "order": 48
    }
  ]
};
